version: "3.9"
services:
  db:
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${WORDPRESS_DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
  wordpress:
    build:
      context: .
    image: it_consultis
    container_name: it_consultis
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - ..:/var/www/html
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - db
volumes:
  db_data:
